### ISSUE TITLE
Class MSP\SecuritySuiteCommon\Model\ConfigMigration does not exist

### ISSUE THREAD

**Issue by moneef** [magespecialist/m2-MSP_Security_Suite_Common#1]
Hey @phoenix128  and @giacmir ,

 whenever i try to compile with `setup:di:compile` i get this error : 

>  [ReflectionException]
>   Class MSP\SecuritySuiteCommon\Model\ConfigMigration does not exist

I cleared the content of var folder, did composer update and composer install, i still get the same error

**Comment by phoenix128** [comment]
Hello @moneef ,
what is the Security Suite module you are trying to install?

**Comment by phoenix128** [comment]
Hello @moneef ,
just got the problem.

You just need to upgrade all the security suite modules you have to the latest version. There is an issue in our composer.json file we are fixing.
